<?php

namespace Database\Seeders;

use App\Models\Family;
use App\Models\Member;
use App\Models\MemberMutation;
use App\Models\Rayon;
use App\Models\DataDictionary;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;

class FamilyAndMemberSeeder extends Seeder
{
    public function run(): void
    {
        // Ambil data dictionaries untuk pemetaan ID
        $houseStatuses = DataDictionary::where('category', 'house_status')->pluck('id', 'code');
        $houseCategories = DataDictionary::where('category', 'house_category')->pluck('id', 'code');
        $familyPositions = DataDictionary::where('category', 'family_position')->pluck('id', 'code');
        $maritalStatuses = DataDictionary::where('category', 'marital_status')->pluck('id', 'code');
        $educations = DataDictionary::where('category', 'education')->pluck('id', 'code');
        $occupations = DataDictionary::where('category', 'occupation')->pluck('id', 'code');
        $membershipStatuses = DataDictionary::where('category', 'membership_status')->pluck('id', 'code');
        $churchRoles = DataDictionary::where('category', 'church_role')->pluck('id', 'code');

        // Ambil Rayons
        $rayons = Rayon::all();
        if ($rayons->isEmpty()) {
            $this->call(RayonSeeder::class);
            $rayons = Rayon::all();
        }

        // Definisi Data KK
        $familiesData = [
            [
                'family_number' => 'KK-2026-0001',
                'rayon_id' => $rayons->where('name', 'Rayon 1 (Matius)')->first()->id ?? $rayons->first()->id,
                'address' => 'Jl. Oepura No. 12, Kupang',
                'phone' => '081123456789',
                'house_status_id' => $houseStatuses['milik-sendiri'] ?? null,
                'house_category_id' => $houseCategories['permanen'] ?? null,
                'notes' => 'Keluarga aktif beribadah.',
                'members' => [
                    [
                        'first_name' => 'Yohanis',
                        'middle_name' => '',
                        'last_name' => 'Ndun',
                        'nik' => '5371011212750001',
                        'phone' => '081123456789',
                        'birth_place' => 'Rote',
                        'birth_date' => '1975-12-12',
                        'gender' => 'L',
                        'family_position_id' => $familyPositions['suami'] ?? null,
                        'marital_status_id' => $maritalStatuses['married'] ?? null,
                        'father_name' => 'Jacob Ndun',
                        'mother_name' => 'Elisabeth Ndun-Lolo',
                        'education_id' => $educations['setara-s1'] ?? null,
                        'occupation_id' => $occupations['pns'] ?? null,
                        'income' => 5500000.00,
                        'church_role_id' => $churchRoles['tidak-menjabat'] ?? null,
                        'membership_status_id' => $membershipStatuses['jemaat'] ?? null,
                        'status_baptis' => true,
                        'baptism_date' => '1976-02-15',
                        'baptism_church' => 'GMIT Syalom Kupang',
                        'baptism_pastor' => 'Pdt. A. M. Toma, S.Th',
                        'baptism_witness_1' => 'Zakharias Ndun',
                        'baptism_witness_2' => 'Helena Bano',
                        'sidi_date' => '1992-05-10',
                        'sidi_church' => 'GMIT Syalom Kupang',
                        'sidi_pastor' => 'Pdt. B. L. Kase, M.Th',
                        'marriage_date' => '2000-06-20',
                        'marriage_church' => 'GMIT Sion Oepura',
                        'marriage_pastor' => 'Pdt. C. Neno, S.Th',
                        'is_deceased' => false,
                    ],
                    [
                        'first_name' => 'Maria',
                        'middle_name' => '',
                        'last_name' => 'Ndun-Bano',
                        'nik' => '5371011508780002',
                        'phone' => '081234567890',
                        'birth_place' => 'Kupang',
                        'birth_date' => '1978-08-15',
                        'gender' => 'P',
                        'family_position_id' => $familyPositions['istri'] ?? null,
                        'marital_status_id' => $maritalStatuses['married'] ?? null,
                        'father_name' => 'Andreas Bano',
                        'mother_name' => 'Martha Bano-Lusi',
                        'education_id' => $educations['tamat-sma-smk'] ?? null,
                        'occupation_id' => $occupations['ibu-rumah-tangga'] ?? null,
                        'income' => 0.00,
                        'church_role_id' => $churchRoles['tidak-menjabat'] ?? null,
                        'membership_status_id' => $membershipStatuses['jemaat'] ?? null,
                        'status_baptis' => true,
                        'baptism_date' => '1978-10-10',
                        'baptism_church' => 'GMIT Kota Kupang',
                        'baptism_pastor' => 'Pdt. J. Rondo, S.Th',
                        'sidi_date' => '1995-04-12',
                        'sidi_church' => 'GMIT Kota Kupang',
                        'sidi_pastor' => 'Pdt. J. Rondo, S.Th',
                        'marriage_date' => '2000-06-20',
                        'marriage_church' => 'GMIT Sion Oepura',
                        'marriage_pastor' => 'Pdt. C. Neno, S.Th',
                        'is_deceased' => false,
                    ],
                    [
                        'first_name' => 'Yeheskiel',
                        'middle_name' => '',
                        'last_name' => 'Ndun',
                        'nik' => '5371012005050003',
                        'phone' => '',
                        'birth_place' => 'Kupang',
                        'birth_date' => '2005-05-20',
                        'gender' => 'L',
                        'family_position_id' => $familyPositions['anak'] ?? null,
                        'marital_status_id' => $maritalStatuses['single'] ?? null,
                        'father_name' => 'Yohanis Ndun',
                        'mother_name' => 'Maria Ndun-Bano',
                        'education_id' => $educations['tamat-smp'] ?? null,
                        'occupation_id' => $occupations['pelajar'] ?? null,
                        'income' => 0.00,
                        'church_role_id' => $churchRoles['tidak-menjabat'] ?? null,
                        'membership_status_id' => $membershipStatuses['jemaat'] ?? null,
                        'status_baptis' => true,
                        'baptism_date' => '2005-08-20',
                        'baptism_church' => 'GMIT Sion Oepura',
                        'baptism_pastor' => 'Pdt. C. Neno, S.Th',
                        'is_deceased' => false,
                    ],
                ]
            ],
            [
                'family_number' => 'KK-2026-0002',
                'rayon_id' => $rayons->where('name', 'Rayon 2 (Markus)')->first()->id ?? $rayons->first()->id,
                'address' => 'RT 02/RW 01, Markus Area, Kupang',
                'phone' => '081298765432',
                'house_status_id' => $houseStatuses['milik-sendiri'] ?? null,
                'house_category_id' => $houseCategories['permanen'] ?? null,
                'notes' => 'Keluarga Pelayan Harian Majelis Jemaat.',
                'members' => [
                    [
                        'first_name' => 'Matheos',
                        'middle_name' => '',
                        'last_name' => 'Dami',
                        'nik' => '5371021010700001',
                        'phone' => '081298765432',
                        'birth_place' => 'Sabu',
                        'birth_date' => '1970-10-10',
                        'gender' => 'L',
                        'family_position_id' => $familyPositions['suami'] ?? null,
                        'marital_status_id' => $maritalStatuses['married'] ?? null,
                        'father_name' => 'Titus Dami',
                        'mother_name' => 'Sarah Dami-Hege',
                        'education_id' => $educations['tamat-sma-smk'] ?? null,
                        'occupation_id' => $occupations['wiraswasta'] ?? null,
                        'income' => 7500000.00,
                        'church_role_id' => $churchRoles['ketua-rayon'] ?? null, // Ketua Rayon
                        'membership_status_id' => $membershipStatuses['penatua'] ?? null, // Penatua
                        'status_baptis' => true,
                        'baptism_date' => '1970-12-25',
                        'baptism_church' => 'GMIT Sabu',
                        'baptism_pastor' => 'Pdt. E. Radja, S.Th',
                        'sidi_date' => '1987-04-15',
                        'sidi_church' => 'GMIT Sabu',
                        'sidi_pastor' => 'Pdt. E. Radja, S.Th',
                        'marriage_date' => '1998-08-18',
                        'marriage_church' => 'GMIT Sion Oepura',
                        'marriage_pastor' => 'Pdt. C. Neno, S.Th',
                        'is_deceased' => false,
                    ],
                    [
                        'first_name' => 'Martha',
                        'middle_name' => '',
                        'last_name' => 'Dami-Lomi',
                        'nik' => '5371022002740002',
                        'phone' => '081345678912',
                        'birth_place' => 'Kupang',
                        'birth_date' => '1974-02-20',
                        'gender' => 'P',
                        'family_position_id' => $familyPositions['istri'] ?? null,
                        'marital_status_id' => $maritalStatuses['married'] ?? null,
                        'father_name' => 'Yonas Lomi',
                        'mother_name' => 'Ribka Lomi-Riwu',
                        'education_id' => $educations['diploma'] ?? null,
                        'occupation_id' => $occupations['pegawai-swasta'] ?? null,
                        'income' => 4500000.00,
                        'church_role_id' => $churchRoles['tidak-menjabat'] ?? null,
                        'membership_status_id' => $membershipStatuses['diaken'] ?? null, // Diaken
                        'status_baptis' => true,
                        'baptism_date' => '1974-04-12',
                        'baptism_church' => 'GMIT Koinonia Kupang',
                        'baptism_pastor' => 'Pdt. H. Ndolu, S.Th',
                        'sidi_date' => '1991-05-10',
                        'sidi_church' => 'GMIT Koinonia Kupang',
                        'sidi_pastor' => 'Pdt. H. Ndolu, S.Th',
                        'marriage_date' => '1998-08-18',
                        'marriage_church' => 'GMIT Sion Oepura',
                        'marriage_pastor' => 'Pdt. C. Neno, S.Th',
                        'is_deceased' => false,
                    ],
                    [
                        'first_name' => 'Yohana',
                        'middle_name' => '',
                        'last_name' => 'Dami',
                        'nik' => '5371020202030003',
                        'phone' => '081234567788',
                        'birth_place' => 'Kupang',
                        'birth_date' => '2003-02-02',
                        'gender' => 'P',
                        'family_position_id' => $familyPositions['anak'] ?? null,
                        'marital_status_id' => $maritalStatuses['single'] ?? null,
                        'father_name' => 'Matheos Dami',
                        'mother_name' => 'Martha Dami-Lomi',
                        'education_id' => $educations['setara-s1'] ?? null,
                        'occupation_id' => $occupations['mahasiswa'] ?? null,
                        'income' => 0.00,
                        'church_role_id' => $churchRoles['guru-sekolah-minggu'] ?? null, // Guru Sekolah Minggu
                        'membership_status_id' => $membershipStatuses['jemaat'] ?? null,
                        'status_baptis' => true,
                        'baptism_date' => '2003-05-15',
                        'baptism_church' => 'GMIT Sion Oepura',
                        'baptism_pastor' => 'Pdt. C. Neno, S.Th',
                        'sidi_date' => '2020-04-12',
                        'sidi_church' => 'GMIT Sion Oepura',
                        'sidi_pastor' => 'Pdt. F. M. Lado, S.Th',
                        'is_deceased' => false,
                    ],
                ]
            ],
            [
                'family_number' => 'KK-2026-0003',
                'rayon_id' => $rayons->where('name', 'Rayon 3 (Lukas)')->first()->id ?? $rayons->first()->id,
                'address' => 'Gg. Damai No. 4, Lukas Area',
                'phone' => '082345678901',
                'house_status_id' => $houseStatuses['sewa-kontrak'] ?? null,
                'house_category_id' => $houseCategories['semi-permanen'] ?? null,
                'notes' => 'Keluarga sederhana, membutuhkan dukungan diakonia.',
                'members' => [
                    [
                        'first_name' => 'Hendrik',
                        'middle_name' => '',
                        'last_name' => 'Rihi',
                        'nik' => '5371031505800001',
                        'phone' => '082345678901',
                        'birth_place' => 'Sumba',
                        'birth_date' => '1980-05-15',
                        'gender' => 'L',
                        'family_position_id' => $familyPositions['suami'] ?? null,
                        'marital_status_id' => $maritalStatuses['married'] ?? null,
                        'father_name' => 'Daud Rihi',
                        'mother_name' => 'Ester Rihi-Dida',
                        'education_id' => $educations['tamat-smp'] ?? null,
                        'occupation_id' => $occupations['buruh'] ?? null,
                        'income' => 1800000.00,
                        'church_role_id' => $churchRoles['tidak-menjabat'] ?? null,
                        'membership_status_id' => $membershipStatuses['jemaat'] ?? null,
                        'status_baptis' => true,
                        'baptism_date' => '1980-08-20',
                        'baptism_church' => 'GKS Waingapu',
                        'baptism_pastor' => 'Pdt. S. M. Lani, S.Th',
                        'sidi_date' => '1997-04-12',
                        'sidi_church' => 'GKS Waingapu',
                        'sidi_pastor' => 'Pdt. S. M. Lani, S.Th',
                        'marriage_date' => '2005-09-10',
                        'marriage_church' => 'GMIT Sion Oepura',
                        'marriage_pastor' => 'Pdt. C. Neno, S.Th',
                        'is_deceased' => false,
                    ],
                    [
                        'first_name' => 'Sarah',
                        'middle_name' => '',
                        'last_name' => 'Rihi-Tallo',
                        'nik' => '5371032210830002',
                        'phone' => '',
                        'birth_place' => 'Kupang',
                        'birth_date' => '1983-10-22',
                        'gender' => 'P',
                        'family_position_id' => $familyPositions['istri'] ?? null,
                        'marital_status_id' => $maritalStatuses['married'] ?? null,
                        'father_name' => 'Jonas Tallo',
                        'mother_name' => 'Martha Tallo-Kase',
                        'education_id' => $educations['tamat-sma-smk'] ?? null,
                        'occupation_id' => $occupations['wiraswasta'] ?? null,
                        'income' => 1200000.00,
                        'church_role_id' => $churchRoles['tidak-menjabat'] ?? null,
                        'membership_status_id' => $membershipStatuses['jemaat'] ?? null,
                        'status_baptis' => true,
                        'baptism_date' => '1983-12-25',
                        'baptism_church' => 'GMIT Sion Oepura',
                        'baptism_pastor' => 'Pdt. C. Neno, S.Th',
                        'sidi_date' => '1999-05-10',
                        'sidi_church' => 'GMIT Sion Oepura',
                        'sidi_pastor' => 'Pdt. C. Neno, S.Th',
                        'marriage_date' => '2005-09-10',
                        'marriage_church' => 'GMIT Sion Oepura',
                        'marriage_pastor' => 'Pdt. C. Neno, S.Th',
                        'is_deceased' => false,
                    ],
                    [
                        'first_name' => 'Samuel',
                        'middle_name' => '',
                        'last_name' => 'Rihi',
                        'nik' => '5371031010100003',
                        'phone' => '',
                        'birth_place' => 'Kupang',
                        'birth_date' => '2010-10-10',
                        'gender' => 'L',
                        'family_position_id' => $familyPositions['anak'] ?? null,
                        'marital_status_id' => $maritalStatuses['single'] ?? null,
                        'father_name' => 'Hendrik Rihi',
                        'mother_name' => 'Sarah Rihi-Tallo',
                        'education_id' => $educations['tidak-lulus-sd'] ?? null,
                        'occupation_id' => $occupations['pelajar'] ?? null,
                        'income' => 0.00,
                        'church_role_id' => $churchRoles['tidak-menjabat'] ?? null,
                        'membership_status_id' => $membershipStatuses['jemaat'] ?? null,
                        'status_baptis' => true,
                        'baptism_date' => '2010-12-25',
                        'baptism_church' => 'GMIT Sion Oepura',
                        'baptism_pastor' => 'Pdt. C. Neno, S.Th',
                        'is_deceased' => false,
                    ],
                ]
            ],
            [
                'family_number' => 'KK-2026-0004',
                'rayon_id' => $rayons->where('name', 'Rayon 4 (Yohanes)')->first()->id ?? $rayons->first()->id,
                'address' => 'Jl. Kenanga No. 8, Yohanes Area',
                'phone' => '085239123456',
                'house_status_id' => $houseStatuses['milik-sendiri'] ?? null,
                'house_category_id' => $houseCategories['permanen'] ?? null,
                'notes' => 'Terdapat anggota keluarga yang telah meninggal (suami).',
                'members' => [
                    [
                        'first_name' => 'Wilhelmina',
                        'middle_name' => '',
                        'last_name' => 'Lado-Kase',
                        'nik' => '5371044411550001',
                        'phone' => '085239123456',
                        'birth_place' => 'Soe',
                        'birth_date' => '1955-11-24',
                        'gender' => 'P',
                        'family_position_id' => $familyPositions['istri'] ?? null, // Saat ini kepala keluarga fungsional
                        'marital_status_id' => $maritalStatuses['widow'] ?? null, // Janda
                        'father_name' => 'Abraham Kase',
                        'mother_name' => 'Helena Kase-Taopan',
                        'education_id' => $educations['tamat-sma-smk'] ?? null,
                        'occupation_id' => $occupations['pensiunan'] ?? null,
                        'income' => 2000000.00,
                        'church_role_id' => $churchRoles['tidak-menjabat'] ?? null,
                        'membership_status_id' => $membershipStatuses['jemaat'] ?? null,
                        'status_baptis' => true,
                        'baptism_date' => '1956-01-20',
                        'baptism_church' => 'GMIT Soe',
                        'baptism_pastor' => 'Pdt. S. J. Neno, S.Th',
                        'sidi_date' => '1972-04-12',
                        'sidi_church' => 'GMIT Soe',
                        'sidi_pastor' => 'Pdt. S. J. Neno, S.Th',
                        'marriage_date' => '1976-10-10',
                        'marriage_church' => 'GMIT Paulus Kupang',
                        'marriage_pastor' => 'Pdt. H. K. Loni, S.Th',
                        'is_deceased' => false,
                    ],
                    [
                        'first_name' => 'David',
                        'middle_name' => '',
                        'last_name' => 'Lado',
                        'nik' => '5371041208800002',
                        'phone' => '085239654321',
                        'birth_place' => 'Kupang',
                        'birth_date' => '1980-08-12',
                        'gender' => 'L',
                        'family_position_id' => $familyPositions['anak'] ?? null,
                        'marital_status_id' => $maritalStatuses['single'] ?? null,
                        'father_name' => 'Johanis Lado',
                        'mother_name' => 'Wilhelmina Lado-Kase',
                        'education_id' => $educations['setara-s1'] ?? null,
                        'occupation_id' => $occupations['wiraswasta'] ?? null,
                        'income' => 4000000.00,
                        'church_role_id' => $churchRoles['tidak-menjabat'] ?? null,
                        'membership_status_id' => $membershipStatuses['jemaat'] ?? null,
                        'status_baptis' => true,
                        'baptism_date' => '1980-10-25',
                        'baptism_church' => 'GMIT Paulus Kupang',
                        'baptism_pastor' => 'Pdt. H. K. Loni, S.Th',
                        'sidi_date' => '1997-05-12',
                        'sidi_church' => 'GMIT Paulus Kupang',
                        'sidi_pastor' => 'Pdt. J. A. Adang, S.Th',
                        'is_deceased' => false,
                    ],
                    // SEEDED DECEASED MEMBER
                    [
                        'first_name' => 'Johanis',
                        'middle_name' => '',
                        'last_name' => 'Lado',
                        'nik' => '5371041005500003',
                        'phone' => '',
                        'birth_place' => 'Kupang',
                        'birth_date' => '1950-05-10',
                        'gender' => 'L',
                        'family_position_id' => $familyPositions['suami'] ?? null,
                        'marital_status_id' => $maritalStatuses['married'] ?? null,
                        'father_name' => 'Petrus Lado',
                        'mother_name' => 'Sara Lado-Bona',
                        'education_id' => $educations['tamat-sma-smk'] ?? null,
                        'occupation_id' => $occupations['pensiunan'] ?? null,
                        'income' => 0.00,
                        'church_role_id' => $churchRoles['tidak-menjabat'] ?? null,
                        'membership_status_id' => $membershipStatuses['jemaat'] ?? null,
                        'status_baptis' => true,
                        'baptism_date' => '1950-07-20',
                        'baptism_church' => 'GMIT Paulus Kupang',
                        'baptism_pastor' => 'Pdt. G. D. Lomi, S.Th',
                        'sidi_date' => '1967-04-12',
                        'sidi_church' => 'GMIT Paulus Kupang',
                        'sidi_pastor' => 'Pdt. G. D. Lomi, S.Th',
                        'marriage_date' => '1976-10-10',
                        'marriage_church' => 'GMIT Paulus Kupang',
                        'marriage_pastor' => 'Pdt. H. K. Loni, S.Th',
                        'is_deceased' => true,
                        'death_date' => '2025-08-15',
                    ],
                ]
            ],
            [
                'family_number' => 'KK-2026-0005',
                'rayon_id' => $rayons->where('name', 'Rayon 5 (Petrus)')->first()->id ?? $rayons->first()->id,
                'address' => 'Jl. El Tari No. 15, Kupang',
                'phone' => '081339998877',
                'house_status_id' => $houseStatuses['milik-sendiri'] ?? null,
                'house_category_id' => $houseCategories['permanen'] ?? null,
                'notes' => 'Keluarga Dokter Jemaat.',
                'members' => [
                    [
                        'first_name' => 'Paulus',
                        'middle_name' => '',
                        'last_name' => 'Radja',
                        'nik' => '5371051203720001',
                        'phone' => '081339998877',
                        'birth_place' => 'Kupang',
                        'birth_date' => '1972-03-12',
                        'gender' => 'L',
                        'family_position_id' => $familyPositions['suami'] ?? null,
                        'marital_status_id' => $maritalStatuses['married'] ?? null,
                        'father_name' => 'Stefanus Radja',
                        'mother_name' => 'Ester Radja-Wadu',
                        'education_id' => $educations['setara-s2'] ?? null,
                        'occupation_id' => $occupations['dokter'] ?? null,
                        'income' => 15000000.00,
                        'church_role_id' => $churchRoles['tidak-menjabat'] ?? null,
                        'membership_status_id' => $membershipStatuses['jemaat'] ?? null,
                        'status_baptis' => true,
                        'baptism_date' => '1972-05-14',
                        'baptism_church' => 'GMIT Koinonia Kupang',
                        'baptism_pastor' => 'Pdt. J. A. Ndun, S.Th',
                        'sidi_date' => '1989-04-12',
                        'sidi_church' => 'GMIT Koinonia Kupang',
                        'sidi_pastor' => 'Pdt. J. A. Ndun, S.Th',
                        'marriage_date' => '1998-05-25',
                        'marriage_church' => 'GMIT Koinonia Kupang',
                        'marriage_pastor' => 'Pdt. K. Bire, S.Th',
                        'is_deceased' => false,
                    ],
                    [
                        'first_name' => 'Debora',
                        'middle_name' => '',
                        'last_name' => 'Radja-Lay',
                        'nik' => '5371052511750002',
                        'phone' => '081234561234',
                        'birth_place' => 'Sabu',
                        'birth_date' => '1975-11-25',
                        'gender' => 'P',
                        'family_position_id' => $familyPositions['istri'] ?? null,
                        'marital_status_id' => $maritalStatuses['married'] ?? null,
                        'father_name' => 'Petrus Lay',
                        'mother_name' => 'Martha Lay-Riwu',
                        'education_id' => $educations['diploma'] ?? null,
                        'occupation_id' => $occupations['bidan'] ?? null,
                        'income' => 6000000.00,
                        'church_role_id' => $churchRoles['tidak-menjabat'] ?? null,
                        'membership_status_id' => $membershipStatuses['jemaat'] ?? null,
                        'status_baptis' => true,
                        'baptism_date' => '1976-01-20',
                        'baptism_church' => 'GMIT Sabu',
                        'baptism_pastor' => 'Pdt. E. Lado, S.Th',
                        'sidi_date' => '1992-04-12',
                        'sidi_church' => 'GMIT Sabu',
                        'sidi_pastor' => 'Pdt. E. Lado, S.Th',
                        'marriage_date' => '1998-05-25',
                        'marriage_church' => 'GMIT Koinonia Kupang',
                        'marriage_pastor' => 'Pdt. K. Bire, S.Th',
                        'is_deceased' => false,
                    ],
                    [
                        'first_name' => 'Timothy',
                        'middle_name' => '',
                        'last_name' => 'Radja',
                        'nik' => '5371051512010003',
                        'phone' => '081234567899',
                        'birth_place' => 'Kupang',
                        'birth_date' => '2001-12-15',
                        'gender' => 'L',
                        'family_position_id' => $familyPositions['anak'] ?? null,
                        'marital_status_id' => $maritalStatuses['single'] ?? null,
                        'father_name' => 'Paulus Radja',
                        'mother_name' => 'Debora Radja-Lay',
                        'education_id' => $educations['tamat-sma-smk'] ?? null,
                        'occupation_id' => $occupations['mahasiswa'] ?? null,
                        'income' => 0.00,
                        'church_role_id' => $churchRoles['tidak-menjabat'] ?? null,
                        'membership_status_id' => $membershipStatuses['jemaat'] ?? null,
                        'status_baptis' => true,
                        'baptism_date' => '2002-02-20',
                        'baptism_church' => 'GMIT Sion Oepura',
                        'baptism_pastor' => 'Pdt. C. Neno, S.Th',
                        'sidi_date' => '2018-04-15',
                        'sidi_church' => 'GMIT Sion Oepura',
                        'sidi_pastor' => 'Pdt. F. M. Lado, S.Th',
                        'is_deceased' => false,
                    ]
                ]
            ],
        ];

        // Seed Families and Members
        foreach ($familiesData as $famData) {
            $family = Family::updateOrCreate(
                ['family_number' => $famData['family_number']],
                [
                    'rayon_id' => $famData['rayon_id'],
                    'address' => $famData['address'],
                    'phone' => $famData['phone'],
                    'house_status_id' => $famData['house_status_id'],
                    'house_category_id' => $famData['house_category_id'],
                    'notes' => $famData['notes'],
                ]
            );

            foreach ($famData['members'] as $memData) {
                Member::updateOrCreate(
                    ['nik' => $memData['nik']],
                    array_merge($memData, ['family_id' => $family->id])
                );
            }
        }

        // SEED MUTATIONS
        // 1. Yoseph Leo (Mari kita buat dummy member Yoseph Leo dahulu untuk mutasi, atau ambil member yang ada)
        // Kita gunakan David Lado (ID 4 - Family 4) untuk Pindah Rayon
        $david = Member::where('first_name', 'David')->first();
        if ($david) {
            MemberMutation::updateOrCreate(
                [
                    'member_id' => $david->id,
                    'document_number' => 'MUT-202605-001'
                ],
                [
                    'mutation_type' => 'Pindah Rayon',
                    'mutation_date' => '2026-05-10',
                    'old_rayon_id' => $rayons->where('name', 'Rayon 4 (Yohanes)')->first()->id ?? $rayons->first()->id,
                    'new_rayon_id' => $rayons->where('name', 'Rayon 1 (Matius)')->first()->id ?? $rayons->first()->id,
                    'reason' => 'Pindah alamat domisili ke rumah baru di wilayah Rayon 1.',
                ]
            );
        }

        // 2. Wilhelmina Lado (Atestasi Masuk)
        $wilhelmina = Member::where('first_name', 'Wilhelmina')->first();
        if ($wilhelmina) {
            MemberMutation::updateOrCreate(
                [
                    'member_id' => $wilhelmina->id,
                    'document_number' => 'MUT-202601-002'
                ],
                [
                    'mutation_type' => 'Atestasi Masuk',
                    'mutation_date' => '2026-01-15',
                    'origin_church' => 'GMIT Paulus Kupang',
                    'destination_church' => 'GMIT Sion Oepura',
                    'reason' => 'Mengikuti perpindahan domisili keluarga.',
                ]
            );
        }
    }
}
